### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by fabriguespe** [open-frames/proxy#16]
Hey,

I'm running into this error while rendering some buttons from popular Frames.

Examples:
Frame: https://fc-polls.vercel.app/polls/87b1ed3f-5f86-479a-acc7-727943eecfe3
Repo: https://github.com/farcasterxyz/fc-polls or https://github.com/xmtp-labs/fc-polls
Button: `Create your poll`

Frame: 
Repo: https://github.com/fabriguespe/a-frame-in-100-lines-main
Frame: https://a-frame-in-100-lines-main.vercel.app/
Buttons: `All`

Live domain
![CleanShot 2024-03-17 at 15 26 19@2x](https://github.com/open-frames/proxy/assets/1447073/5f17514b-97cd-49c2-80ed-ded5dd54f121)

Localhost:
![CleanShot 2024-03-15 at 18 17 05@2x](https://github.com/open-frames/proxy/assets/1447073/944b6bae-3ac8-4753-b29f-e667db50c748)

Environment:
- Client: https://dev-inbox.vercel.app/
- Repo: https://github.com/xmtp/dev-inbox.git

**Comment by davidfurlong** [comment]
Some ways to solve this
- run proxy on the same origin
- configure the CORS rules to allow this request - not sure exactly which rule where would solve this though, would have to look at it more closely

**Comment by neekolas** [comment]
I believe what's happening here is that we are only setting CORS headers on success but not on error. That causes the true source of these errors to be hidden (which is that we are sending POST requests that the servers don't understand and the remote server is returning an error status code)

**Comment by alexrisch** [comment]
@fabriguespe Agreeing with @neekolas here there is an error happening so the CORS headers aren't getting se. If we bypass the proxy it will also error, this is because a few of these frames don't support Open Frames POSTs
https://github.com/fabriguespe/a-frame-in-100-lines/blob/main/app/api/frame/route.ts#L9
